#!/bin/sh

sudo pacman -S --needed --noconfirm base-devel
git clone https://aur.archlinux.org/paru.git initparu
sh -c "cd 'initparu' && makepkg -si"
sudo rm -r initparu && sudo rm -r $HOME/.cargo

git clone https://github.com/koalagang/dotfiles.git
sudo pacman -Syu

# Stuff I may or may not wish to install:
#"udisks2" # I'm considering using Luke Smith's dmenu script instead
#"calcurse"
#"pass"
#"ufw"
#"neofetch"
#"libresprite" # probably won't use this because I have Aseprite on Steam
#"godot-mono-bin" # probably not yet because it's still in alpha

#"xautolock" or "xidlehook"??

official=(
    "wget"
    "libx11"
    "libxinerama"
    "curl"
    "git"
    "ueberzug"
    "cronie"
    "cronie-runit"
    "ffmpeg"
    "unzip"
    "make"
    "openvpn"
    "adobe-source-han-sans-otc-fonts"
    "adobe-source-han-serif-otc-fonts"
    "gnu-free-fonts"
    "ttf-liberation"
    "ttf-linux-libertine"
    "ttf-ubuntu-font-family"
    "noto-fonts-emoji"
    "opendoas"
    "pulseaudio"
    "youtube-dl"
    "mpv"
    "zathura"
    "zathura-pdf-mupdf"
    "pandoc"
    "texlive-core"
    "keepassxc"
    "anki"
    "libreoffice-still"
    "gimp"
    "dash"
    "zsh"
    "zsh-syntax-highlighting"
    "zsh-autosuggestions"
    "pkgfile"
    "signal-desktop"
    "groff"
    "nvidia-lts"
    "nvidia-dkms"
    "nvidia-utils"
    "lib32-nvidia-utils"
    "nvidia-settings"
    "wine-staging"
    "giflib"
    "lib32-giflib"
    "libpng"
    "lib32-libpng"
    "libldap"
    "lib32-libldap"
    "gnutls"
    "lib32-gnutls"
    "mpg123"
    "lib32-mpg123"
    "openal"
    "lib32-openal"
    "v4l-utils"
    "lib32-v4l-utils"
    "libpulse"
    "lib32-libpulse"
    "libgpg-error"
    "lib32-libgpg-error"
    "alsa-plugins"
    "lib32-alsa-lib"
    "libjpeg-turbo"
    "lib32-libjpeg-turbo"
    "sqlite"
    "lib32-sqlite"
    "libxcomposite"
    "lib32-libxcomposite"
    "libxinerama"
    "lib32-xinerama"
    "lib32-libgcrypt"
    "libgcrypt"
    "ncurses"
    "lib32-ncurses"
    "opencl-icd-loader"
    "lib32-opencl-icd-loader"
    "libxslt"
    "lib32-libxslt"
    "libva"
    "lib32-libva"
    "gtk3"
    "lib32-gtk3"
    "gst-plugins-base-libs"
    "lib32-gst-plugins-base-libs"
    "vulkan-icd-loader"
    "lib32-vulkan-icd-loader"
    "lutris"
    "meson"
    "dbus"
    "libinih"
    "steam"
    "vifm"
    "maim"
    "pacman-contrib"
    "unclutter"
    "neovim"
    "alacritty"
    "hsetroot"
    "sxhkd"
    "xdotool"
    "xdo"
    "xclip"
    "fd"
    "bat"
    "ripgrep"
    "exa"
    "virtualbox"
    "python-psutil"
    "lm_sensors"
    "alsa-utils"
    "lxsession"
    "newsboat"
    "legendary"
    "itch"
    "multimc5"
    "starship"
    "network-manager-applet"
    "picom"
    "dunst"
    "trash-cli"
    "xorg-xinit"
    "xdg-user-dirs"
    "mpd"
    "mpd-runit"
    "ncmpcpp"
    "playerctl"
    "lollypop"
    "translate-shell"
    "arch-wiki-docs"
    "github-cli"
    "lynx"
    "streamlink"
    "shellcheck"
    "godot"
    "lmms"
)

aur=(
    "bottom-bin"
    "timeshift-bin"
    "z.lua"
    "so"
    "mpdris2"
    "zsh-you-should-use"
    "vim-plug"
    "ytfzf"
    "grap"
    "spacefm"
    "simple-mtpfs"
    "devour"
    "ucollage"
    "colorpicker"
    "python-readability-lxml"
    "python-spotdl"
    "redshift-minimal"
    "tuxi-git"
    "spotify"
    "librewolf-bin"
    "sc-im"
    "id3"
    "protonvpn-cli-ng"
    "pipe-viewer-git"
    "papirus-folders-git"
    "glow-bin"
    "dragon-drag-and-drop"
    "quich"
    "nerd-fonts-hack"
    "discord_arch_electron"
)

sudo pacman -S --noconfirm --needed "${offical[@]}"
paru -S --noconfirm --needed "${aur[@]}"

echo "post-installation script complete!"
printf "\nTo switch to a binary version of paru, you must manually enter:\n`paru -S paru-bin`\nYou may also wish to logout or restart for certain changes to take affect.\n"
